# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 11.0.3, 11 ]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/javassist/javassist/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_21
    - run: rm starting_build_uses-checkout_21
    - uses: actions/checkout@v2
    - run: touch starting_build_SetupJDKmatrixjavaversion_22
    - run: rm starting_build_SetupJDKmatrixjavaversion_22
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
    - run: touch starting_build_BuildwithMaven_27
    - run: rm starting_build_BuildwithMaven_27
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/javassist/javassist/target/rat.txt ]; then cat /home/runner/work/javassist/javassist/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/javassist/javassist/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/javassist/javassist/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},javassist,${GITHUB_WORKFLOW}" > /home/runner/work/javassist/javassist/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: javassist
        ref: '1686785308-548a464'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p javassist/javassist/.github/workflows/maven/build_os_${{ matrix.os }}_java-version_${{ matrix.java-version }}
        cp -rvT optimizing-ci-builds-ci-analysis javassist/javassist/.github/workflows/maven/build_os_${{ matrix.os }}_java-version_${{ matrix.java-version }}
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1686785308-548a464/javassist/.github/workflows/maven/build_os_${{ matrix.os }}_java-version_${{ matrix.java-version }}
    - name: Pushes analysis to another repository
      if: always()
      working-directory: javassist
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1686785308-548a464; do
          git pull --rebase origin 1686785308-548a464
          sleep $((RANDOM % 5 + 1))
        done
