name: Java CI with Maven
on: [push]
jobs:
  build_os_ubuntu-latest_java-version_11.0.3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java-version:
        - 11.0.3
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/javassist/javassist/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_buildosubuntulatestjavaversion1103_uses-checkout_19
    - run: rm starting_buildosubuntulatestjavaversion1103_uses-checkout_19
    - uses: actions/checkout@v2
    - run: touch starting_buildosubuntulatestjavaversion1103_SetupJDKmatrixjavaversion_20
    - run: rm starting_buildosubuntulatestjavaversion1103_SetupJDKmatrixjavaversion_20
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: zulu
    - run: touch starting_buildosubuntulatestjavaversion1103_BuildwithMaven_25
    - run: rm starting_buildosubuntulatestjavaversion1103_BuildwithMaven_25
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'javassist/.github/workflows/maven/buildosubuntulatestjavaversion1103'
  build_os_ubuntu-latest_java-version_11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java-version:
        - 11
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/javassist/javassist/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_buildosubuntulatestjavaversion11_uses-checkout_36
    - run: rm starting_buildosubuntulatestjavaversion11_uses-checkout_36
    - uses: actions/checkout@v2
    - run: touch starting_buildosubuntulatestjavaversion11_SetupJDKmatrixjavaversion_37
    - run: rm starting_buildosubuntulatestjavaversion11_SetupJDKmatrixjavaversion_37
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: zulu
    - run: touch starting_buildosubuntulatestjavaversion11_BuildwithMaven_42
    - run: rm starting_buildosubuntulatestjavaversion11_BuildwithMaven_42
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'javassist/.github/workflows/maven/buildosubuntulatestjavaversion11'

